// Generates every published token artifact from src/tokens.json:
//   dist/tokens.css          CSS custom properties, light + dark themes
//   dist/tokens.json         nested, aliases resolved
//   dist/tokens.flat.json    flat "color.action.primary" -> value map
//   src/generated/tokens.ts  typed `as const` objects consumed by src/index.ts
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const PREFIX = 'mrd'
const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const source = JSON.parse(readFileSync(join(root, 'src/tokens.json'), 'utf8'))

const isToken = (node) =>
  node !== null && typeof node === 'object' && typeof node.value === 'string'

/** Depth-first walk yielding one entry per leaf token. */
function collect(node, path = []) {
  if (isToken(node)) return [{ path, ...node }]
  return Object.entries(node)
    .filter(([key]) => !key.startsWith('$'))
    .flatMap(([key, child]) => collect(child, [...path, key]))
}

const tokens = collect(source)
const byPath = new Map(tokens.map((token) => [token.path.join('.'), token]))

const ALIAS = /^\{([^}]+)\}$/

/** Resolves `{color.brand.500}` alias chains for a theme, falling back to light. */
function resolve(raw, theme, seen = new Set()) {
  const match = ALIAS.exec(raw)
  if (!match) return raw
  const target = match[1]
  if (seen.has(target)) {
    throw new Error(`Circular token alias: ${[...seen, target].join(' -> ')}`)
  }
  const token = byPath.get(target)
  if (!token) throw new Error(`Unknown token alias: {${target}}`)
  const next = theme === 'dark' ? (token.dark ?? token.value) : token.value
  return resolve(next, theme, new Set(seen).add(target))
}

const kebab = (segment) => segment.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
const cssVar = (path) => `--${PREFIX}-${path.map(kebab).join('-')}`

const entries = tokens.map((token) => ({
  name: token.path.join('.'),
  path: token.path,
  variable: cssVar(token.path),
  value: resolve(token.value, 'light'),
  dark: token.dark === undefined ? undefined : resolve(token.dark, 'dark'),
}))

// --- CSS --------------------------------------------------------------------
const declarations = (theme, pad = '  ') =>
  entries
    .filter((entry) => theme === 'light' || entry.dark !== undefined)
    .map((entry) => `${pad}${entry.variable}: ${theme === 'dark' ? entry.dark : entry.value};`)
    .join('\n')

const css = `/* Generated by @meridian/tokens — do not edit by hand. */
:root {
${declarations('light')}
}

/* An explicit data-theme choice wins over the OS preference. */
[data-theme='dark'] {
${declarations('dark')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${declarations('dark', '    ')}
  }
}
`

// --- JSON -------------------------------------------------------------------
const nested = {}
for (const entry of entries) {
  let cursor = nested
  for (const segment of entry.path.slice(0, -1)) {
    cursor[segment] ??= {}
    cursor = cursor[segment]
  }
  cursor[entry.path.at(-1)] = {
    value: entry.value,
    ...(entry.dark === undefined ? {} : { dark: entry.dark }),
    variable: entry.variable,
  }
}

const flat = Object.fromEntries(entries.map((entry) => [entry.name, entry.value]))

// --- Typed TS module --------------------------------------------------------
/** Rebuilds the nested shape as a TS literal, keeping the original key casing. */
function tsLiteral(pick, indent = '') {
  const tree = {}
  for (const entry of entries) {
    const picked = pick(entry)
    if (picked === undefined) continue
    let cursor = tree
    for (const segment of entry.path.slice(0, -1)) {
      cursor[segment] ??= {}
      cursor = cursor[segment]
    }
    cursor[entry.path.at(-1)] = picked
  }
  const render = (node, pad) =>
    typeof node === 'string'
      ? JSON.stringify(node)
      : `{\n${Object.entries(node)
          .map(([key, child]) => `${pad}  ${JSON.stringify(key)}: ${render(child, `${pad}  `)},`)
          .join('\n')}\n${pad}}`
  return render(tree, indent)
}

const ts = `// Generated by scripts/build-tokens.mjs — do not edit by hand.
// Run \`pnpm --filter @meridian/tokens generate\` after editing src/tokens.json.

/** Resolved light-theme values, keyed by token path. */
export const tokens = ${tsLiteral((entry) => entry.value)} as const

/** Values that differ in the dark theme. */
export const darkTokens = ${tsLiteral((entry) => entry.dark)} as const

/** CSS custom property name for every token, e.g. \`--${PREFIX}-color-action-primary\`. */
export const cssVariables = ${tsLiteral((entry) => entry.variable)} as const

/** Flat lookup: \`"color.action.primary"\` -> resolved light value. */
export const flatTokens = {
${entries.map((entry) => `  ${JSON.stringify(entry.name)}: ${JSON.stringify(entry.value)},`).join('\n')}
} as const
`

mkdirSync(join(root, 'dist'), { recursive: true })
mkdirSync(join(root, 'src/generated'), { recursive: true })
writeFileSync(join(root, 'dist/tokens.css'), css)
writeFileSync(join(root, 'dist/tokens.json'), `${JSON.stringify(nested, null, 2)}\n`)
writeFileSync(join(root, 'dist/tokens.flat.json'), `${JSON.stringify(flat, null, 2)}\n`)
writeFileSync(join(root, 'src/generated/tokens.ts'), ts)

console.log(`tokens: generated ${entries.length} tokens (css, json, flat json, ts)`)
